# Netlify Configuration File

# This redirect rule makes clean URLs like `/insights/posts/my-first-post/` work.
# It serves the `blog-post.html` template without changing the browser URL.
# The JavaScript in that file then reads the URL to fetch the correct content.

[[redirects]]
  from = "/insights/posts/*"
  to = "/insights/blog-post.html"
  status = 200